apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: projet-cluster
  region: us-east-1
nodeGroups:
  - name: ng
    instanceType: t3a.medium
    desiredCapacity: 1
    volumeSize: 80
    iam:
      instanceRoleARN: arn:aws:iam::846733227578:role/LabRole
iam:
  serviceRoleARN: arn:aws:iam::846733227578:role/LabRole
